name: "Generate EcmaScript bindings"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: sudo apt-get install -y -q asciidoctor pandoc

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: install typedoc
      run: sudo npm install -g typedoc

    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: setup git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: generate sources
      run: mvn -B generate-sources

    - name: generated manual
      run: |
        rm -Rf manual
        mkdir -p manual
        cd target
        find "manual" -maxdepth 1 -type f -name "*.adoc" -print0 |
          while IFS= read -r -d '' line; do
            manual="${line%.*}"
            echo "Processing $manual ..."
            # Convert asciidoc to docbook using asciidoctor
            asciidoctor -b docbook "${manual}.adoc"
            # foo.xml will be output into the same directory as foo.adoc
            iconv -t utf-8 "${manual}.xml" | pandoc -f docbook -t gfm | iconv -f utf-8 > "${manual}.md"
            # Copy to the target
            cp "${manual}.md" ../manual/
          done

        git add manual
        git commit -m "Save generated manual changes" -a

    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}